// Developed by Hirnyk Vlad (HERN1k)

import type { ReactNode, ComponentType } from "react";
import type { Request } from "./request";
import type { Response } from "./response";
import type { DB } from "./db";
import type { Render } from "./render";
import type { Config } from "./config";
import type { Logger } from "./logger";

/**
 * Props passed to the main application Layout component.
 */
type LayoutProps = {
    /** Page title displayed in the browser tab */
    title: string; 
    /** ISO language code for the HTML lang attribute (e.g., 'en', 'uk') */
    lang: string;
    /** Raw HTML content or rendered string from React components */
    content: string;
    /** Array of CSS file paths to be included in the <head> */
    css: Array<string>;
    /** Array of JS file paths to be included before </body> */
    js: Array<string>;
};

/**
 * Result of the route parsing process.
 * Contains decomposed information about the current URL.
 */
type ParserResult = {
    /** Flag indicating if the request belongs to the administrative panel */
    isAdmin: boolean;
    /** Application root directory: 'admin' or 'catalog' */
    path: string;
    /** Subdirectory within the controller folder (e.g., 'common', 'product') */
    folder: string;
    /** The controller class filename (without .ts/.tsx extension) */
    file: string;
    /** The specific method name to be executed within the controller */
    action: string;
    /** The full raw route string used for internal lookups */
    route: string;
};

/**
 * Structure of a file uploaded via multipart/form-data.
 */
interface IUploadedFile {
    /** Original filename provided by the client, e.g., 'photo.jpg' */
    name: string;    
    /** MIME type of the file, e.g., 'image/jpeg' */
    type: string;     
    /** Absolute path to the temporary file on the server (Bun/Node temp dir) */
    tmpName: string;   
    /** File size in bytes */
    size: number;    
    /** Sanitized file extension in lowercase (without leading dot) */
    extension: string;
    /** Upload error code. 0 indicates success, non-zero values represent PHP-style upload errors */
    error: number;
}

/**
 * Core Registry data structure.
 * Stores shared instances and global application state for the current request.
 */
interface IRegistryData {
    /** Current HTTP request instance */
    request: Request;
    /** Current HTTP response instance */
    response: Response;
    /** Database manager instance */
    db: DB;
    /** Current HTTP request config */
    config: Config,
    /** React render instance */
    render: Render;
    /** Allows dynamic registration of additional services or parameters */
    [key: string]: any;
}

/**
 * Represents a UI component block registered in the Render engine.
 */
interface IComponentBlock {
    /** The React component class or function to be rendered */
    component: ComponentType<any>;
    /** Properties to be passed specifically to this component instance */
    props: any;
    /** Execution order within the slot. Lower values are rendered first (Ascending) */
    priority: number;
}

/**
 * Interface defining the standard structure for all Cache Drivers.
 * Supports both synchronous (Memory) and asynchronous (File, Redis) operations.
 */
interface ICacheDriver {
    /** * Stores a value in the cache. 
     * @param key - Unique cache identifier.
     * @param value - Data to store.
     * @returns True on success, or a Promise resolving to success state.
     */
    set<T>(key: string, value: T): boolean | Promise<boolean>;
    
    /** * Retrieves a value by key. 
     * @param key - Unique cache identifier.
     * @returns The cached value, null if expired, or undefined if not found.
     */
    get<T>(key: string): T | null | undefined | Promise<T | null | undefined>;
    
    /** * Retrieves all valid cache entries currently stored by the driver.
     * @returns Array of key-value pairs.
     */
    getAll(): Record<string, any>[] | Promise<Record<string, any>[]>;
    
    /** * Removes a specific entry by its key. 
     * @param key - Unique cache identifier.
     */
    remove(key: string): boolean | Promise<boolean>;
    
    /** * Completely wipes the cache storage associated with this driver.
     */
    clear(): boolean | Promise<boolean>;

    /**
     * Index signature for driver-specific methods.
     */
    [key: string]: any;
}

/**
 * Interface for database drivers.
 * Provides a unified abstraction for SQL-based engines.
 */
interface IDBDriver {
    /** Executes a raw SQL query. */
    query(sql: string): Promise<IDBResult>;
    /** Escapes strings to prevent SQL Injection. */
    escape(value: string): string;
    /** Returns the ID generated by the last INSERT query. */
    getLastId(): number;
    /** Closes the database connection. */
    close(): void;
}

/**
 * Standard database result format returned by IDBDriver.
 */
interface IDBResult {
    /** Array of objects representing the rows returned by the query */
    rows: any[];
    /** The total number of rows affected or returned */
    numRows: number;
}

/**
 * Represents a cached item structure for persistent storage.
 * @template T - The type of the stored value.
 */
type CacheItem<T> = {
    /** The actual data stored in the cache */
    value: T;
    /** Expiration timestamp in seconds (Unix Timestamp) */
    tte: number;
};

/**
 * Configuration for adding a view block using a file path.
 */
export type RenderPathOptions = {
    /** Path to the view file (e.g., 'common/header') */
    path: string;
    /** Target slot name (e.g., 'header', 'content') */
    slot?: string;
    /** Component properties (props) */
    props?: any;
    /** Execution order (lower renders first) */
    priority?: number;
};

/**
 * Configuration for adding a block using an existing React Component.
 */
export type RenderComponentOptions = {
    /** Valid React Component type */
    component: ComponentType<any> | null | undefined;
    /** Target slot name (defaults to 'main') */
    slot?: string;
    /** Component properties (props) */
    props?: any;
    /** Execution order (defaults to 100) */
    priority?: number;
};

/**
 * Standard properties passed to React Page components.
 */
interface IPageProps {
    /** Storage for key-value string data */
    data: Map<string, string>;
    /** Helper to retrieve string data */
    get: (key: string) => string;
    /** Helper to retrieve data of any type */
    any: (key: string) => any;
    /** Support for dynamic properties */
    [key: string]: any;
}

/**
 * Global application configuration settings.
 */
interface IConfig {
    /** Current active theme name */
    theme: string;
    /** Current active system language */
    lang: string;
    /** Additional configuration entries */
    [key: string]: any;
}

/**
 * Application performance and usage statistics.
 */
interface IAppStats {
    /** Cumulative number of requests processed since startup */
    totalRequests: number;
    /** Counter for HTTP methods (GET, POST, etc.) */
    methods: Record<string, number>;
    /** Counter for HTTP status codes returned */
    statusCodes: Record<number, number>;
    /** Server startup time (Unix Timestamp) */
    startTime: number;
    /** Unique visitor IP addresses */
    uniqueIps: Set<string>;
    /** Detailed per-IP activity log */
    ipActivity: Record<string, {
        count: number,
        lastUrl: string,
        lastMethod: string,
        lastSeen: string
    }>;
}

/**
 * Server disk usage information.
 */
interface IDiskInfo {
    /** Total disk capacity */
    total: string;
    /** Available free space */
    free: string;
    /** Percentage of used disk space */
    usedPercent: string;
}

/**
 * Supported output formats for image processing.
 */
type ImageFormat = 'webp' | 'jpeg' | 'png' | 'avif';